<Project>
	<PropertyGroup>
		<MinVerMinimumMajorMinor>3.0</MinVerMinimumMajorMinor>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MinVer">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
		</PackageReference>

		<PackageReference Include="Microsoft.SourceLink.GitHub">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
		</PackageReference>

		<PackageReference Include="DotNet.ReproducibleBuilds">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
		</PackageReference>
	</ItemGroup>
</Project>