<Project>
	<PropertyGroup>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
	</PropertyGroup>

    <ItemGroup>
        <PackageVersion Include="MinVer" Version="7.0.0" />
		<PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.103" />
		<PackageVersion Include="DotNet.ReproducibleBuilds" Version="2.0.2" />
        <PackageVersion Include="JetBrains.Annotations" Version="2025.2.4" />
    </ItemGroup>


    <ItemGroup>
        <PackageVersion Include="System.DirectoryServices" Version="10.0.3" Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net10.0'))" />
        <PackageVersion Include="System.DirectoryServices" Version="9.0.10" Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net9.0')) AND !$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net10.0'))" />
        <PackageVersion Include="System.DirectoryServices" Version="8.0.0" Condition="!$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net9.0'))" />

		<PackageVersion Include="System.Security.Cryptography.Xml" Version="10.0.3" Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net10.0'))" />
		<PackageVersion Include="System.Security.Cryptography.Xml" Version="9.0.10" Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net9.0')) AND !$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net10.0'))" />
		<PackageVersion Include="System.Security.Cryptography.Xml" Version="8.0.2" Condition="!$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net9.0'))" />

		<PackageVersion Include="DnsClient" Version="1.8.0" />
    </ItemGroup>

    <ItemGroup>
	    <PackageVersion Include="TUnit" Version="1.15.0" />

		<PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.3" />

		<PackageVersion Include="Microsoft.Extensions.Configuration" Version="10.0.3" />
		<PackageVersion Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.3" />

		<PackageVersion Include="Microsoft.Extensions.Options" Version="10.0.3" />
		<PackageVersion Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.3" />

        <PackageVersion Include="Microsoft.Identity.Client" Version="4.82.1" />
	    <PackageVersion Include="Microsoft.Identity.Web.TokenCache" Version="4.3.0"/>
    </ItemGroup>
</Project>